### ISSUE TITLE
bug: component height problem

### ISSUE THREAD

**Issue by ydedev** [paul-thebaud/v-phone-input#12]
Thanks for your contribution, this project helped me a lot.

## Expected Behavior

highly consistent

## Actual Behavior
![1](https://github.com/paul-thebaud/v-phone-input/assets/136344088/6e693988-d420-414e-bd88-33ba4358fc8f)

The area code input box is 2px lower

## Steps to Reproduce the Problem

  1.comment out  “  //app.component('VAutocomplete', VAutocomplete);”
 and  " //enableSearchingCountry: true,"

```
//app.component('VAutocomplete', VAutocomplete);
const vPhoneInput = createVPhoneInput({
  //enableSearchingCountry: true,
});
```
Area code input box shrinks when search is turned off

## Specifications

  - OS: win10
  - Browser: chrome
    "@mdi/font": "7.2.96",
    "core-js": "^3.31.0",
    "flag-icons": "^6.7.0",
    "roboto-fontface": "*",
    "v-phone-input": "^3.0.4",
    "vue": "^3.3.4",
    "vue-router": "^4.2.2",
    "vuetify": "^3.3.5",
    "webfontloader": "^1.6.28"

and How to set the width of the search box in the search state
![2](https://github.com/paul-thebaud/v-phone-input/assets/136344088/8639aaea-9ba1-4563-87ef-531b74d5c583)

**Comment by ydedev** [comment]
test code : [test-v-phone-input](https://github.com/ydedev/test-v-phone-input)

**Comment by paul-thebaud** [comment]
Hi @ydedev, thanks for this complete and precise issue.
The bug should be fixed with latest Vuetify version and `v-phone-input@3.0.5` (latest) :tada: 
With this release, you can also quickly impact the country autocomplete width using a CSS variable: `--v-phone-input-country-autocomplete-width`. The default value is `70%` of the input full width.
